export const tasks = [
  {
    title: 'Task Title 1',
    description: 'This is task description. Demo description for task 1',
    dueDate: '2024-03-31T12:00:00.000Z',
    status: 'active',
    priority: 'Low',
    reactions: {
      thumbsUp: 0,
      wow: 0,
      heart: 0,
      rocket: 0,
    },
  },
  {
    title: 'Task Title 2',
    description: 'This is task description. Demo description for task 2',
    dueDate: '2024-04-15T12:00:00.000Z',
    status: 'completed',
    priority: 'Medium',
    reactions: {
      thumbsUp: 0,
      wow: 0,
      heart: 0,
      rocket: 0,
    },
  },
  {
    title: 'Task Title 3',
    description: 'This is task description. Demo description for task 3',
    dueDate: '2024-05-10T12:00:00.000Z',
    status: 'active',
    priority: 'High',
    reactions: {
      thumbsUp: 0,
      wow: 0,
      heart: 0,
      rocket: 0,
    },
  },
  {
    title: 'Task Title 4',
    description: 'This is task description. Demo description for task 4',
    dueDate: '2024-06-05T12:00:00.000Z',
    status: 'completed',
    priority: 'Low',
    reactions: {
      thumbsUp: 0,
      wow: 0,
      heart: 0,
      rocket: 0,
    },
  },
  {
    title: 'Task Title 5',
    description: 'This is task description. Demo description for task 5',
    dueDate: '2024-07-20T12:00:00.000Z',
    status: 'active',
    priority: 'Medium',
    reactions: {
      thumbsUp: 0,
      wow: 0,
      heart: 0,
      rocket: 0,
    },
  },
  {
    title: 'Task Title 6',
    description: 'This is task description. Demo description for task 6',
    dueDate: '2024-08-15T12:00:00.000Z',
    status: 'completed',
    priority: 'High',
    reactions: {
      thumbsUp: 0,
      wow: 0,
      heart: 0,
      rocket: 0,
    },
  },
  {
    title: 'Task Title 7',
    description: 'This is task description. Demo description for task 7',
    dueDate: '2024-09-30T12:00:00.000Z',
    status: 'active',
    priority: 'Low',
    reactions: {
      thumbsUp: 0,
      wow: 0,
      heart: 0,
      rocket: 0,
    },
  },
  {
    title: 'Task Title 8',
    description: 'This is task description. Demo description for task 8',
    dueDate: '2024-10-15T12:00:00.000Z',
    status: 'completed',
    priority: 'Medium',
    reactions: {
      thumbsUp: 0,
      wow: 0,
      heart: 0,
      rocket: 0,
    },
  },
  {
    title: 'Task Title 9',
    description: 'This is task description. Demo description for task 9',
    dueDate: '2024-11-10T12:00:00.000Z',
    status: 'active',
    priority: 'High',
    reactions: {
      thumbsUp: 0,
      wow: 0,
      heart: 0,
      rocket: 0,
    },
  },
  {
    title: 'Task Title 10',
    description: 'This is task description. Demo description for task 10',
    dueDate: '2024-12-05T12:00:00.000Z',
    status: 'completed',
    priority: 'Low',
    reactions: {
      thumbsUp: 0,
      wow: 0,
      heart: 0,
      rocket: 0,
    },
  },
];
